name: Setup platform
description: Sets up Java and Gradle.

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v6
      with:
        distribution: temurin
        java-version: 26

    - uses: gradle/actions/setup-gradle@v6
      with:
        add-job-summary: 'never'
