version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gradle
    directory: /platform
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /platform
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - '*'
